### ISSUE TITLE
Vue-iframes.js: Uncaught ReferenceError: uuid is not defined

### ISSUE THREAD

**Issue by akolliy1** [Chantouch/vue-iframes#30]
I installed the iframe to use, then registered it  correctly but I got the error in the screenshot below

> The below is the entry file where I registered it. I later installed Uuid maybe that would solve it but still same
```
import Vue from 'vue'
import '@babel/polyfill'
import VueIframe from 'vue-iframes'
import UUID from "vue-uuid";
import router from './router'
import store from './store'

Vue.use(UUID);
Vue.use(VueIframe)

Vue.config.productionTip = false

new Vue({
  router,
  store,
  render: h => h(App),
}).$mount('#app')

```
<img width="1439" alt="Screenshot 2021-03-27 at 12 15 32 PM" src="https://user-images.githubusercontent.com/31921958/112719020-d2859180-8ef6-11eb-8f56-cc49b730db20.png">
<img width="1439" alt="Screenshot 2021-03-27 at 12 24 07 PM" src="https://user-images.githubusercontent.com/31921958/112719119-67888a80-8ef7-11eb-9da0-e682cdffc3d0.png">

**Comment by sctouch** [comment]
@akolliy1 what is your `Vue` version?

**Comment by sctouch** [comment]
@akolliy1 thank for report, plz use version 0.0.16, it will be fixed.
