### ISSUE TITLE
Need Help Disabling Scrolling

### ISSUE THREAD

**Issue by dnandakumarcyber** [Chantouch/vue-iframes#33]
Hi, I'm new to vue and need help on how I can disable scrolling for the iframe. 
I have this currently as props when initializing: 

            src="URL"
            frame-id="my-ifram"
            name="my-frame"
            height="300px"

What should I add to disable scrolling?

**Comment by sctouch** [comment]
@dnandakumarcyber can i have your screenshot of that?

**Comment by srxa** [comment]
Try with scrolling="no"

**Comment by sctouch** [comment]
@srxa but basically, it already added into iframe.

**Comment by srxa** [comment]
I think that default value is null, not "no".

**Comment by sctouch** [comment]
@srxa ohh, great. if that was fixed the issue is ok. thank you.

**Comment by sctouch** [comment]
@dnandakumarcyber can u confirm your issue, is it help you?
