### ISSUE TITLE
access iframe content

### ISSUE THREAD

**Issue by eli007s** [Chantouch/vue-iframes#7]
when running

`this.iframe = frame.contentWindow`
`this.iframe.document.body.innerHTML`

it returns

```
<script>
  window.document.onreadystatechange = function () {
    if (window.document.readyState === 'complete') {
      parent.postMessage('IFRAME_ON_READ_STATE_CHANGE_12f03cf2-9d09-4430-8e2e-8d88c60408ac', '*')
    }
  };
</script>
```

what needs to be done to return the content of the loaded iframe?

**Comment by Chantouch** [comment]
@eli007s so do you want to access html content ?

**Comment by gilfuser** [comment]
Hi there! Do you mind reopen this issue?
Well, it's not really an issue, is more a how-to.

I would like to access the css classes in the html inside the iframe, but couldn't find a way to do it.
I'm fiddling inside the onload(frame) as @eli007s.

My goal is to remove a div in the html, selecting it through its class, but it should work to change or add a style.

best regards,
Gil

**Comment by chantouchsek** [comment]
what is the plan to remove a div inside html element ?

**Comment by sctouch** [comment]
@gilfuser did you try to access sit by `$refs`?

**Comment by gilfuser** [comment]
Hi @Chantouch. Yes, I did.

**Comment by sctouch** [comment]
@chris-aeviator  yes, it might be so too.
